---
:constants:
  :blue_white: [224, 224, 255]
  :very_dark_blue: [0, 0, 100]
  :dark_blue: [50, 50, 150]
  :light_blue: [150, 150, 255]

:elements:
  :Element:
    :font_name: UnmaskedBB.ttf
    :font_height: 20
    :color: ?blue_white
    :background_color: ?none
    :border_color: ?light_blue

  :Button:
    :disabled:
      :background_color: ?very_dark_blue
      :border_color: ?dark_blue
    :hover:
      :background_color: ?light_blue

  :Packer:
    :spacing_h: 8
    :spacing_v: 8
    :padding_left: 16
    :padding_right: 16
    :padding_top: 12
    :padding_bottom: 18

  :Button:
    :border_thickness: 2
    :padding_left: 12
    :padding_right: 12
    :padding_top: 4
    :padding_bottom: 4
    :background_color: ?dark_blue

  :ComboBox:
    :border_thickness: 0

  :MenuPane::Item:
    :padding_top: 0.4
    :padding_bottom: 0.4

  :ToolTip:
    :font_height: 16
    :padding_top: 4
    :padding_bottom: 4
    :background_color: ?very_dark_blue

  :TextArea:
    :color: ?blue_white
    :background_color: ?very_dark_blue
    
  :ScrollBar: # < Composite
    :rail_width: 14
    
  :ScrollWindow: # < Composite
    :scroll_bar_thickness: 14
    :border_color: ?dark_blue

