---

:blunt:
  :affects: :health_points
  :spritesheet_column: 0
  :color: [225, 255, 255]
  :sides:
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1

:cosmic:
  :status: :irradiated
  :spritesheet_column: 8
  :color: [0, 0, 20]
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1


:electric:
  :affects: :health_points
  :spritesheet_column: 3
  :color: [51, 51, 255]
  :sides:
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1


:fire:
  :status: :burning
  :spritesheet_column: 1
  :color: [255, 0, 0]
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1


:hold:
  :status: :held
  :spritesheet_column: 6
  :color: [0, 220, 220]
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1

:impaling:
  :affects: :health_points
  :spritesheet_column: 4
  :color: [240, 240, 0]
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 1
    - 2


:knockback:
  # Special effect
  :spritesheet_column: 7
  :color: [140, 0, 158]
  :sides:
    - 0
    - 0
    - 1
    - 1
    - 2
    - 2


:mental:
  :status: :stunned
  :spritesheet_column: 5
  :color: [255, 139, 153]
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1


:poison:
  :status: :poisoned
  :spritesheet_column: 2
  :color: [0, 200, 0]
  :sides:
    - 0
    - 0
    - 1
    - 1
    - 1
    - 1