---

:blunt:
  :affects: :health_points
  :spritesheet_column: 0
  :sides:
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1

:cosmic:
  :status: :irradiated
  :spritesheet_column: 8
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1


:electric:
  :affects: :health_points
  :spritesheet_column: 3
  :sides:
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1


:fire:
  :status: :burning
  :spritesheet_column: 1
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1


:hold:
  :status: :held
  :spritesheet_column: 6
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1

:impaling:
  :affects: :health_points
  :spritesheet_column: 4
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 1
    - 2


:knockback:
  # Special effect
  :spritesheet_column: 7
  :sides:
    - 0
    - 0
    - 1
    - 1
    - 2
    - 2


:mental:
  :status: :stunned
  :spritesheet_column: 5
  :sides:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1


:poison:
  :status: :poisoned
  :spritesheet_column: 2
  :sides:
    - 0
    - 0
    - 1
    - 1
    - 1
    - 1