---

# === ENTITIES CONFIG ===
# Entities are mobile people and creatures, which can be moved by player/AI.

# === BADDIES ===

# - Supervillains -

:green_goddess:
  :faction: :baddies
  :spritesheet_position: [5, 4]
  :movement_points: 10
  :action_points: 2
  :health_points: 6
  :abilities:
    -
      :type: :melee
      :skill: 3
    -
      :type: :ranged
      :skill: 2
      :max_range: 5
    -
      :type: :sprint
      :skill: 4


:octobrain: # Scientist with giant brain.
  :faction: :baddies
  :spritesheet_position: [7, 3]
  :visible_sprite_height: 28
  :movement_points: 6
  :action_points: 2
  :health_points: 4
  :abilities:
    -
      :type: :melee
      :skill: 1
    -
      :type: :ranged
      :skill: 4
      :max_range: 2
    -
      :type: :sprint
      :skill: 1

:femme_fatale: # Woman in red dress.
  :faction: :baddies
  :spritesheet_position: [7, 1]
  :movement_points: 8
  :action_points: 2
  :health_points: 5
  :abilities:
    -
      :type: :melee
      :skill: 2
    -
      :type: :sprint
      :skill: 2

:radioactive_gorilla:
  :faction: :baddies
  :spritesheet_position: [1, 4]
  :visible_sprite_height: 34
  :movement_points: 8
  :action_points: 2
  :health_points: 9
  :abilities:
    -
      :type: :melee
      :skill: 4
    -
      :type: :sprint
      :skill: 1

:robot:
  :faction: :baddies
  :spritesheet_position: [0, 4]
  :visible_sprite_height: 36
  :movement_points: 5
  :action_points: 2
  :health_points: 10
  :abilities:
    -
      :type: :melee
      :skill: 5

:artist:
  :faction: :baddies
  :spritesheet_position: [3, 2]
  :movement_points: 8
  :action_points: 2
  :health_points: 5
  :abilities:
    -
      :type: :melee
      :skill: 2
    -
      :type: :sprint
      :skill: 3

:invisible_man:
  :faction: :baddies
  :spritesheet_position: [7, 4]
  :movement_points: 7
  :action_points: 2
  :health_points: 5
  :abilities:
    -
      :type: :melee
      :skill: 2
    -
      :type: :sprint
      :skill: 3

:professor_goggles:
  :faction: :baddies
  :spritesheet_position: [2, 4]
  :movement_points: 7
  :action_points: 2
  :health_points: 5
  :abilities:
    -
      :type: :melee
      :skill: 2
    -
      :type: :ranged
      :skill: 4
      :max_range: 10
    -
      :type: :sprint
      :skill: 2

:yuri_blastin:
  :faction: :baddies
  :spritesheet_position: [6, 5]
  :visible_sprite_height: 22
  :movement_points: 6
  :action_points: 2
  :health_points: 6
  :abilities:
    -
      :type: :melee
      :skill: 1
    -
      :type: :ranged
      :skill: 5
      :max_range: 15

# - Minions -

# === GOODIES ===

# - Cops, G-men and Soldiers -

:cop_with_gun:
  :faction: :goodies
  :spritesheet_position: [0, 0]
  :movement_points: 8
  :action_points: 1
  :health_points: 4
  :abilities:
    -
      :type: :melee
      :skill: 1
    -
      :type: :ranged
      :skill: 2
      :max_range: 6
    -
      :type: :sprint
      :skill: 2

:g_man_coat_with_gun:
  :faction: :goodies
  :spritesheet_position: [5, 0]
  :movement_points: 8
  :action_points: 1
  :health_points: 4
  :abilities:
    -
      :type: :melee
      :skill: 2
    -
      :type: :ranged
      :skill: 2
      :max_range: 8
    -
      :type: :sprint
      :skill: 2

:g_man_shirt_with_gun:
  :faction: :goodies
  :spritesheet_position: [6, 0]
  :movement_points: 8
  :action_points: 1
  :health_points: 4
  :abilities:
    -
      :type: :melee
      :skill: 2
    -
      :type: :ranged
      :skill: 2
      :max_range: 8
    -
      :type: :sprint
      :skill: 2

:soldier_with_gun:
  :faction: :goodies
  :spritesheet_position: [3, 0]
  :movement_points: 8
  :action_points: 1
  :health_points: 4
  :abilities:
    -
      :type: :melee
      :skill: 1
    -
      :type: :ranged
      :skill: 3
      :min_range: 3
      :max_range: 9
    -
      :type: :sprint
      :skill: 2

:soldier_with_bazooka:
  :faction: :goodies
  :spritesheet_position: [4, 0]
  :movement_points: 6
  :action_points: 1
  :health_points: 4
  :abilities:
    -
      :type: :melee
      :skill: 1
    -
      :type: :ranged
      :skill: 4
      :min_range: 4
      :max_range: 8

# - Superheroes -

:catman:
  :faction: :goodies
  :spritesheet_position: [4, 1]
  :movement_points: 10
  :action_points: 2
  :health_points: 5
  :abilities:
    -
      :type: :melee
      :skill: 3
    -
      :type: :sprint
      :skill: 5

:enormous_esme: # Giant.
  :faction: :goodies
  :spritesheet_position: [5, 5]
  :visible_sprite_height: 36
  :movement_points: 8
  :action_points: 2
  :health_points: 8
  :abilities:
    -
      :type: :melee
      :skill: 4
    -
      :type: :sprint
      :skill: 2

:femme_fatale2: # Woman in green dress.
  :faction: :goodies
  :spritesheet_position: [6, 1]
  :movement_points: 8
  :action_points: 2
  :health_points: 5
  :abilities:
    -
      :type: :melee
      :skill: 2
    -
      :type: :sprint
      :skill: 2

:homerun: # Baseball player
  :faction: :goodies
  :spritesheet_position: [2, 2]
  :movement_points: 10
  :action_points: 2
  :health_points: 6
  :abilities:
    -
      :type: :melee
      :skill: 4
    -
      :type: :sprint
      :skill: 4

:knockout: # Boxer.
  :faction: :goodies
  :spritesheet_position: [5, 1]
  :movement_points: 8
  :action_points: 2
  :health_points: 8
  :abilities:
    -
      :type: :melee
      :skill: 4
    -
      :type: :sprint
      :skill: 2

:moleman:
  :faction: :goodies
  :spritesheet_position: [0, 2]
  :movement_points: 7
  :action_points: 2
  :health_points: 7
  :abilities:
    -
      :type: :melee
      :skill: 2
    -
      :type: :sprint
      :skill: 1

:mountie: # Canadian Mountie.
  :faction: :goodies
  :spritesheet_position: [0, 5]
  :movement_points: 8
  :action_points: 2
  :health_points: 7
  :abilities:
    -
      :type: :melee
      :skill: 3
    -
      :type: :sprint
      :skill: 2

:spandexman: # Guy in red spandex.
  :faction: :goodies
  :spritesheet_position: [3, 1]
  :movement_points: 8
  :action_points: 2
  :health_points: 10
  :abilities:
    -
      :type: :melee
      :skill: 4
    -
      :type: :sprint
      :skill: 3

:stinger: # Wasp-lady
  :faction: :goodies
  :spritesheet_position: [1, 2]
  :movement_points: 8
  :action_points: 2
  :health_points: 6
  :abilities:
    -
      :type: :melee
      :skill: 3
    -
      :type: :sprint
      :skill: 3

# === BYSTANDERS ===

# - Newspaper -

:boy_selling_papers:
  :faction: :bystanders
  :spritesheet_position: [6, 4]
  :visible_sprite_height: 20
  :movement_points: 7
  :action_points: 0
  :health_points: 1
  :abilities: []

:editor:
  :faction: :bystanders
  :spritesheet_position: [5, 2]
  :movement_points: 6
  :action_points: 0
  :health_points: 2
  :abilities: []

:photographer:
  :faction: :bystanders
  :spritesheet_position: [7, 0]
  :movement_points: 8
  :action_points: 0
  :health_points: 2
  :abilities: []

:reporter:
  :faction: :bystanders
  :spritesheet_position: [0, 1]
  :movement_points: 8
  :action_points: 0
  :health_points: 2
  :abilities: []

# - Other innocents and children

:assistant:
  :faction: :bystanders
  :spritesheet_position: [3, 4]
  :movement_points: 8
  :action_points: 0
  :health_points: 2
  :abilities: []

:boy_with_slingshot:
  :faction: :bystanders
  :spritesheet_position: [1, 1]
  :visible_sprite_height: 20
  :movement_points: 7
  :action_points: 0
  :health_points: 2
  :abilities: []

:girl_with_balloon:
  :faction: :bystanders
  :spritesheet_position: [2, 1]
  :visible_sprite_height: 20
  :movement_points: 7
  :action_points: 0
  :health_points: 2
  :abilities: []