---

# === ENTITIES CONFIG ===
# Entities are mobile people and creatures, which can be moved by player/AI.

# === BADDIES ===

# - Supervillains -

:green_goddess:
  :faction: :baddies
  :spritesheet_position: [5, 4]
  :movement_points: 10
  :action_points: 1
  :health_points: 6
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 3
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 2
      :max_range: 5
      :damage_types:
        - :impaling
        - :poison
    -
      :type: :sprint
      :skill: 4
  :resistances:
    :impaling: 1
  :vulnerabilities:
    :hold: 1


:octobrain: # Scientist with giant brain.
  :faction: :baddies
  :spritesheet_position: [7, 3]
  :visible_sprite_height: 28
  :movement_points: 6
  :action_points: 1
  :health_points: 4
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 1
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 4
      :max_range: 2
      :damage_types:
        - :poison
        - :fire
    -
      :type: :sprint
      :skill: 1
  :vulnerabilities:
    :mental: 1

:femme_fatale: # Woman in red dress.
  :faction: :baddies
  :spritesheet_position: [7, 1]
  :movement_points: 8
  :action_points: 1
  :health_points: 5
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 2
      :damage_types:
        - :blunt
    -
      :type: :sprint
      :skill: 2

:radioactive_gorilla:
  :faction: :baddies
  :spritesheet_position: [1, 4]
  :visible_sprite_height: 34
  :movement_points: 8
  :action_points: 1
  :health_points: 9
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 4
      :damage_types:
        - :blunt
        - :cosmic
    -
      :type: :sprint
      :skill: 1
  :resistances:
    :cosmic: 2
  :vulnerabilities:
    :fire: 2

:robot:
  :faction: :baddies
  :spritesheet_position: [0, 4]
  :visible_sprite_height: 36
  :movement_points: 5
  :action_points: 1
  :health_points: 10
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 5
      :damage_types:
        - :impaling
        - :blunt
  :resistances:
    :mental: Inf
    :poison: Inf
  :vulnerabilities:
    :electric: 2

:artist:
  :faction: :baddies
  :spritesheet_position: [3, 2]
  :movement_points: 8
  :action_points: 1
  :health_points: 5
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 2
      :damage_types:
        - :blunt
    -
      :type: :sprint
      :skill: 3

:invisible_man:
  :faction: :baddies
  :spritesheet_position: [7, 4]
  :movement_points: 7
  :action_points: 1
  :health_points: 5
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 2
      :damage_types:
        - :blunt
    -
      :type: :sprint
      :skill: 3

:professor_goggles:
  :faction: :baddies
  :spritesheet_position: [2, 4]
  :movement_points: 7
  :action_points: 1
  :health_points: 5
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 2
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 4
      :max_range: 10
      :damage_types:
        - :impaling
        - :fire
    -
      :type: :sprint
      :skill: 2
  :resistances:
    :electric: 1

:yuri_blastin:
  :faction: :baddies
  :spritesheet_position: [6, 5]
  :visible_sprite_height: 22
  :movement_points: 6
  :action_points: 1
  :health_points: 6
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 1
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 5
      :max_range: 15
      :damage_types:
        - :cosmic
        - :hold
  :resistances:
    :blunt: 1
    :knockback: 1

# - Minions -

# === GOODIES ===

# - Cops, G-men and Soldiers -

:cop_with_gun:
  :faction: :goodies
  :spritesheet_position: [0, 0]
  :movement_points: 8
  :action_points: 1
  :health_points: 4
  :energy_points: 0
  :abilities:
    -
      :type: :melee
      :skill: 1
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 2
      :max_range: 6
      :damage_types:
        - :impaling
    -
      :type: :sprint
      :skill: 2

:g_man_coat_with_gun:
  :faction: :goodies
  :spritesheet_position: [5, 0]
  :movement_points: 8
  :action_points: 1
  :health_points: 4
  :energy_points: 0
  :abilities:
    -
      :type: :melee
      :skill: 2
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 2
      :max_range: 8
      :damage_types:
        - :impaling
    -
      :type: :sprint
      :skill: 2

:g_man_shirt_with_gun:
  :faction: :goodies
  :spritesheet_position: [6, 0]
  :movement_points: 8
  :action_points: 1
  :health_points: 4
  :energy_points: 0
  :abilities:
    -
      :type: :melee
      :skill: 2
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 2
      :max_range: 8
      :damage_types:
        - :impaling
    -
      :type: :sprint
      :skill: 2

:soldier_with_gun:
  :faction: :goodies
  :spritesheet_position: [3, 0]
  :movement_points: 8
  :action_points: 1
  :health_points: 4
  :energy_points: 0
  :abilities:
    -
      :type: :melee
      :skill: 1
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 3
      :min_range: 3
      :max_range: 9
      :damage_types:
        - :impaling
    -
      :type: :sprint
      :skill: 2

:soldier_with_bazooka:
  :faction: :goodies
  :spritesheet_position: [4, 0]
  :movement_points: 6
  :action_points: 1
  :health_points: 4
  :energy_points: 0
  :abilities:
    -
      :type: :melee
      :skill: 1
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 4
      :min_range: 4
      :max_range: 8
      :damage_types:
        - :blunt
        - :knockback

# - Superheroes -

:catman:
  :faction: :goodies
  :spritesheet_position: [4, 1]
  :movement_points: 10
  :action_points: 1
  :health_points: 5
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 3
      :damage_types:
        - :impaling
    -
      :type: :sprint
      :skill: 5
  :resistances:
    :impaling: 1
  :vulnerabilities:
    :knockback: 1

:enormous_esme: # Giant.
  :faction: :goodies
  :spritesheet_position: [5, 5]
  :visible_sprite_height: 36
  :movement_points: 8
  :action_points: 1
  :health_points: 8
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 4
      :damage_types:
        - :blunt
        - :knockback
    -
      :type: :sprint
      :skill: 2

  :resistances:
    :knockback: 2

:femme_fatale2: # Woman in green dress.
  :faction: :goodies
  :spritesheet_position: [6, 1]
  :movement_points: 8
  :action_points: 1
  :health_points: 5
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 2
      :damage_types:
        - :blunt
    -
      :type: :sprint
      :skill: 2

:homerun: # Baseball player
  :faction: :goodies
  :spritesheet_position: [2, 2]
  :movement_points: 10
  :action_points: 1
  :health_points: 6
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 3
      :damage_types:
        - :blunt
    -
      :type: :ranged
      :skill: 3
      :max_range: 8
      :damage_types:
        - :blunt
    -
      :type: :sprint
      :skill: 4

:knockout: # Boxer.
  :faction: :goodies
  :spritesheet_position: [5, 1]
  :movement_points: 8
  :action_points: 1
  :health_points: 8
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 4
      :damage_types:
        - :blunt
    -
      :type: :sprint
      :skill: 2
  :resistances:
    :blunt: 1
  :vulnerabilities:
    :mental: 1

:moleman:
  :faction: :goodies
  :spritesheet_position: [0, 2]
  :movement_points: 7
  :action_points: 1
  :health_points: 7
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 2
      :damage_types:
        - :impaling
    -
      :type: :sprint
      :skill: 1

:mountie: # Canadian Mountie.
  :faction: :goodies
  :spritesheet_position: [0, 5]
  :movement_points: 8
  :action_points: 1
  :health_points: 7
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 3
      :damage_types:
        - :blunt
    -
      :type: :sprint
      :skill: 2
  :resistances:
    :mental: 1

:spandexman: # Guy in red spandex.
  :faction: :goodies
  :spritesheet_position: [3, 1]
  :movement_points: 8
  :action_points: 1
  :health_points: 10
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 4
      :damage_types:
        - :blunt
    -
      :type: :sprint
      :skill: 3
  :resistances:
    :impaling: 2
  :vulnerabilities:
    :cosmic: 2

:stinger: # Wasp-lady
  :faction: :goodies
  :spritesheet_position: [1, 2]
  :movement_points: 8
  :action_points: 1
  :health_points: 6
  :energy_points: 2
  :abilities:
    -
      :type: :melee
      :skill: 3
      :damage_types:
        - :impaling
        - :poison
    -
      :type: :ranged
      :skill: 2
      :max_range: 5
      :damage_types:
        - :impaling
        - :poison
    -
      :type: :sprint
      :skill: 3
  :resistances:
    :poison: 1
  :vulnerabilities:
    :crushing: 1

# === BYSTANDERS ===

# - Newspaper -

:boy_selling_papers:
  :faction: :bystanders
  :spritesheet_position: [6, 4]
  :visible_sprite_height: 20
  :movement_points: 7
  :action_points: 0
  :health_points: 1
  :energy_points: 0
  :abilities: []

:editor:
  :faction: :bystanders
  :spritesheet_position: [5, 2]
  :movement_points: 6
  :action_points: 0
  :health_points: 2
  :energy_points: 0
  :abilities: []

:photographer:
  :faction: :bystanders
  :spritesheet_position: [7, 0]
  :movement_points: 8
  :action_points: 0
  :health_points: 2
  :energy_points: 0
  :abilities: []

:reporter:
  :faction: :bystanders
  :spritesheet_position: [0, 1]
  :movement_points: 8
  :action_points: 0
  :health_points: 2
  :energy_points: 0
  :abilities: []

# - Other innocents and children

:assistant:
  :faction: :bystanders
  :spritesheet_position: [3, 4]
  :movement_points: 8
  :action_points: 0
  :health_points: 2
  :energy_points: 0
  :abilities: []

:boy_with_slingshot:
  :faction: :bystanders
  :spritesheet_position: [1, 1]
  :visible_sprite_height: 20
  :movement_points: 7
  :action_points: 0
  :health_points: 2
  :energy_points: 0
  :abilities: []

:girl_with_balloon:
  :faction: :bystanders
  :spritesheet_position: [2, 1]
  :visible_sprite_height: 20
  :movement_points: 7
  :action_points: 0
  :health_points: 2
  :energy_points: 0
  :abilities: []