---

# === BADDIES ===

# - Supervillains -

octobrain: # Scientist with giant brain.
  faction: baddies
  spritesheet_position: [7, 3]
  movement_points: 3
  action_points: 2
  health: 5

femme_fatale: # Woman in red dress.
  faction: baddies
  spritesheet_position: [7, 1]
  movement_points: 4
  action_points: 4
  health: 8

radioactive_gorilla:
  faction: baddies
  spritesheet_position: [1, 4]
  movement_points: 4
  action_points: 6
  health: 15

robot:
  faction: baddies
  spritesheet_position: [0, 4]
  movement_points: 2
  action_points: 4
  health: 10

artist:
  faction: baddies
  spritesheet_position: [3, 2]
  movement_points: 4
  action_points: 4
  health: 10

invisible_man:
  faction: baddies
  spritesheet_position: [7, 4]
  movement_points: 4
  action_points: 2
  health: 10

professor_goggles:
  faction: baddies
  spritesheet_position: [2, 4]
  movement_points: 4
  action_points: 2
  health: 8

# - Minions -

# === GOODIES ===

# - Cops -

cop_with_gun:
  faction: goodies
  spritesheet_position: [0, 0]
  movement_points: 4
  action_points: 2
  health: 5

# - Superheroes -

catman:
  faction: goodies
  spritesheet_position: [4, 1]
  movement_points: 6
  action_points: 4
  health: 8

homerun: # Baseball player
  faction: goodies
  spritesheet_position: [2, 2]
  movement_points: 5
  action_points: 4
  health: 10

moleman:
  faction: goodies
  spritesheet_position: [0, 2]
  movement_points: 3
  action_points: 4
  health: 12

the_mountie: # Canadian Mountie.
  faction: goodies
  spritesheet_position: [0, 5]
  movement_points: 4
  action_points: 4
  health: 10

spandexman: # Guy in red spandex.
  faction: goodies
  spritesheet_position: [3, 1]
  movement_points: 4
  action_points: 4
  health: 15

stinger: # Wasp-lady
  faction: goodies
  spritesheet_position: [1, 2]
  movement_points: 4
  action_points: 4
  health: 10

knockout: # Boxer.
  faction: goodies
  spritesheet_position: [5, 1]
  movement_points: 4
  action_points: 6
  health: 10

# === BYSTANDERS ===

# - Newspaper -

boy_selling_papers:
  faction: bystanders
  spritesheet_position: [6, 4]
  movement_points: 3
  action_points: 0
  health: 1

editor:
  faction: bystanders
  spritesheet_position: [5, 2]
  movement_points: 3
  action_points: 0
  health: 2

photographer:
  faction: bystanders
  spritesheet_position: [7, 0]
  movement_points: 4
  action_points: 0
  health: 2

reporter:
  faction: bystanders
  spritesheet_position: [0, 1]
  movement_points: 4
  action_points: 0
  health: 2

# - Other innocents and children

assistant:
  faction: bystanders
  spritesheet_position: [3, 4]
  movement_points: 4
  action_points: 0
  health: 2

boy_with_slingshot:
  faction: bystanders
  spritesheet_position: [1, 1]
  movement_points: 3
  action_points: 0
  health: 2

girl_with_balloon:
  faction: bystanders
  spritesheet_position: [2, 1]
  movement_points: 3
  action_points: 0
  health: 2