---

Entity:
  # Entities are mobile people and creatures, which can be moved by player/AI.
  
  # === BADDIES ===
  
  # - Supervillains -


  artist:
    name: The Painter
    title: Fine art forger
  
  femme_fatale: # Woman in red dress.
    name: Felicity X
    title: Scheming Femme Fatale

  green_goddess:
    name: Green Goddess
    title: Nefarious ninja from Nebraska
  
  invisible_man:
    name: Hiro Nosimi
    title: Invisible man

  octobrain: # Scientist with giant brain.
    name: Octobrain
    title: Mastermind with the brains of eight men
  
  professor_goggles:
    name: Prof. Goggles
    title: Demented scientist

  radioactive_gorilla:
    name: Atom Ape
    title: Radioactive gorrila

  robot:
    name: Bobby
    title: 'Robot B. - Deranged automaton'

  yuri_blastin:
    name: Yuri Blastin
    title: Soviet physisict
  
  # - Minions -
  
  # === GOODIES ===
  
  # - Cops, G-men and Soldiers -
  
  cop_with_gun:
    name: Cop
    title: Law enforcement
  
  g_man_coat_with_gun:
    name: G-Man
    title: Federal agent
  
  g_man_shirt_with_gun:
    name: G-Man
    title: Federal agent
  
  soldier_with_gun:
    name: Soldier
    title: Military
  
  soldier_with_bazooka:
    name: Bazooka soldier
    title: Military
  
  # - Superheroes -
  
  catman:
    name: Cat Man
    title: Notorious cat burgler

  enormous_esme: # Giant
    name: Enormous Esme
    title: Unusually large woman
  
  femme_fatale2: # Woman in green dress.
    name: Olivia Dupres
    title: Femme Fatale
  
  homerun: # Baseball player
    name: Homerun
    title: Retired baseball legend

  knockout: # Boxer.
    name: Knock-out
    title: Has-been pugilist
  
  moleman:
    name: The Mole Man
    title: Infiltrator
  
  mountie: # Canadian Mountie.
    name: The Mountie
    title: Foreign law enforcement who lost his horse
  
  spandexman: # Guy in red spandex.
    name: Spandexman
    title: Legendary superhero
  
  stinger: # Wasp-lady
    name: Stinger
    title: Waspish beatnick
  
  # === BYSTANDERS ===
  
  # - Newspaper -
  
  boy_selling_papers:
    name: Paper-boy
    title: Read all about it!
  
  editor:
    name: "O'Malley"
    title: Editor for the Daily Clarion
  
  photographer:
    name: Peter Panto
    title: Works for the Daily Clarion
  
  reporter:
    name: Clara Kandinski
    title: Reporter for the Daily Clarion
  
  # - Other innocents and children
  
  assistant:
    name: Beril Neville
    title: Assistant scientist
  
  boy_with_slingshot:
    name: Sam
    title: Mischievious tomboy with slingshot
  
  girl_with_balloon:
    name: Sue
    title: Has a nice balloon